# Generated by Django 3.2.8 on 2021-12-30 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='author_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
