# Generated by Django 3.2.8 on 2021-10-28 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20211028_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forum',
            old_name='time_modifed',
            new_name='time_modified',
        ),
    ]
