# Generated by Django 3.2.8 on 2021-10-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=30)),
                ('Date', models.DateTimeField()),
                ('Media', models.CharField(max_length=30)),
                ('Deskripsi', models.TextField()),
            ],
        ),
    ]
