# Generated by Django 3.2.7 on 2021-10-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Card_Image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
