# Generated by Django 3.2.7 on 2021-10-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_event_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Card_Image',
            field=models.ImageField(blank=True, null=True, upload_to='images/event'),
        ),
    ]
