# Generated by Django 3.2.7 on 2021-10-29 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_event_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Page_Image',
            field=models.ImageField(blank=True, null=True, upload_to='images/event'),
        ),
    ]
