# Generated by Django 3.2.8 on 2021-10-30 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('first_option', models.CharField(max_length=50)),
                ('second_option', models.CharField(max_length=50)),
                ('third_option', models.CharField(max_length=50)),
                ('first_option_count', models.IntegerField(default=0)),
                ('second_option_count', models.IntegerField(default=0)),
                ('third_option_count', models.IntegerField(default=0)),
            ],
        ),
    ]
