# Generated by Django 3.2.8 on 2021-11-02 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mini_survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=75)),
            ],
        ),
        migrations.RemoveField(
            model_name='survey',
            name='first_option',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='first_option_count',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='second_option',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='second_option_count',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='third_option',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='third_option_count',
        ),
        migrations.AddField(
            model_name='survey',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='survey',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini_survey.option')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini_survey.survey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini_survey.survey'),
        ),
    ]
